"""
Genesis Core V7: The Portal Pillar (Genesis Hub)

A user-friendly Streamlit interface for non-technical users to interact
with the Genesis ecosystem.
"""
import streamlit as st
import requests
import time

# --- Configuration ---
API_URL = "http://127.0.0.1:8000" # The URL of our FastAPI backend

# Friendly names for experts to improve UX
EXPERT_MAP = {
    "dummy_adapters/expert_A/adapter_model.bin": "Research Assistant (Expert A)",
    "dummy_adapters/expert_B/adapter_model.bin": "Data Analyst (Expert B)",
    "dummy_adapters/expert_C/adapter_model.bin": "Security Auditor (Expert C)"
}

# --- Helper Functions ---
def query_genesis_backend(instruction, experts):
    """
    Simulates a query to the backend. In a real V7 system, this would
    call a dispatch endpoint that uses the Chimera Core. For this PoC,
    we'll simulate the response and get a dispatch_id.
    """
    st.info(f"Querying with experts: {experts}...")

    try:
        # Simulate network latency
        time.sleep(2)
        mock_dispatch_id = f"dispatch_{int(time.time())}"
        mock_response_text = f"This is a simulated response for your query about '{instruction[:30]}...' using experts {experts}."

        # Store which experts were used for this dispatch locally
        if 'dispatch_history' not in st.session_state:
            st.session_state.dispatch_history = {}
        st.session_state.dispatch_history[mock_dispatch_id] = experts

        return mock_dispatch_id, mock_response_text
    except Exception as e:
        st.error(f"Error simulating backend response: {e}")
        return None, None

def send_feedback_to_backend(dispatch_id, score):
    """Sends the user's feedback score to the backend API."""
    try:
        feedback_url = f"{API_URL}/feedback/{dispatch_id}"
        response = requests.post(feedback_url, json={"score": score})
        if response.status_code == 200:
            st.toast(f"Feedback ({score}/1.0) submitted successfully!", icon="✨")
            # Clear the last response to be ready for the next query
            st.session_state.last_response = None
            time.sleep(1) # Brief pause to let the user see the toast
            st.rerun()
        else:
            st.error(f"Failed to submit feedback. Server responded with: {response.status_code}")
            st.json(response.json())
    except requests.exceptions.RequestException as e:
        st.error(f"Error connecting to the backend: {e}")

# --- Streamlit UI ---
st.set_page_config(page_title="Genesis Hub", page_icon="🌌", layout="wide")

st.title("🌌 Genesis Hub")
st.caption("The Portal to the Genesis Symbiotic Network")

# --- Initialization ---
if 'last_response' not in st.session_state:
    st.session_state.last_response = None

# --- Main Interaction Panel ---
st.header("1. Submit a Query")

# For this demo, we'll let the user "choose" the experts.
# In a real system, the Oracle Brain would do this automatically.
available_experts = list(EXPERT_MAP.keys())
selected_experts = st.multiselect(
    "Select Experts to Consult (simulation):",
    options=available_experts,
    default=available_experts[:2],
    format_func=lambda x: EXPERT_MAP.get(x, x)
)

user_instruction = st.text_area(
    "Enter your instruction or question:",
    placeholder="e.g., Summarize the latest research on P2P gossip networks...",
    help="Type your request here. The Genesis expert network will process it and provide a response."
)

if st.button("Query Genesis", disabled=not user_instruction or not selected_experts, type="primary"):
    with st.spinner("Dispatching query to the expert network..."):
        dispatch_id, response_text = query_genesis_backend(user_instruction, selected_experts)
        if dispatch_id and response_text:
            st.session_state.last_response = {
                "dispatch_id": dispatch_id,
                "text": response_text,
                "experts": selected_experts
            }

# --- Feedback Panel ---
if st.session_state.last_response:
    st.divider()
    st.header("2. Provide Feedback")

    response_data = st.session_state.last_response

    st.write("Generated Response:")
    with st.chat_message("assistant", avatar="🌌"):
        st.markdown(response_data["text"])
        st.caption(f"Generated by: {', '.join([EXPERT_MAP.get(e, e) for e in response_data['experts']])}")
        st.caption(f"Dispatch ID: {response_data['dispatch_id']}")

    st.write("How would you rate this response?")

    feedback_score = st.slider("Rating", 0.0, 1.0, 0.75, 0.05, help="Slide to rate the quality of the response.")

    # Dynamic sentiment indicator
    sentiment_map = [
        (0.9, "🤩 Exceptional"),
        (0.7, "😊 Great"),
        (0.5, "🙂 Good"),
        (0.3, "😐 Okay"),
        (0.0, "☹️ Poor")
    ]
    sentiment_label = next(label for score, label in sentiment_map if feedback_score >= score)
    st.info(f"Your selection: **{sentiment_label}** ({feedback_score})")

    if st.button("Submit Feedback", type="primary"):
        # Register the simulated dispatch ID with the backend so it can process feedback
        try:
            register_url = f"{API_URL}/feedback/register_mock_dispatch"
            requests.post(register_url, json={
                "dispatch_id": response_data['dispatch_id'],
                "experts": response_data['experts']
            }, timeout=2)
        except Exception:
             # If registration fails, we still attempt to send feedback
             pass

        send_feedback_to_backend(response_data["dispatch_id"], feedback_score)
